[package]
name = "greenmote"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[features]
default = ["gui"]
gui = ["dep:eframe", "dep:rfd"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6.1"
clap_mangen = "0.3.0"
eframe = { version = "0.34.3", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"], optional = true }
rfd = { version = "0.17.2", optional = true }
rayon = "1.12.0"
regex = "1.12.3"
rapier3d = { version = "0.32.0", default-features = false, features = ["dim3", "f32"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "1.1.2"
glam = "=0.30.10"

[dependencies.openmw-config]
version = "1.0.4"

[dependencies.vfstool_lib]
version = "0.9.0"
features = ["beth-archives"]

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
branch = "main"
features = ["esp", "nif"]
